### ISSUE TITLE
Issue when `resolvedExternals` is empty

### ISSUE THREAD

**Issue by wassim-ben-amor** [MilanKovacic/vite-plugin-externalize-dependencies#108]
Hello,
I am facing an issue using the library on a monorepo where I have many vue3 applications.
The issue happens when there is no matched externals.

After debugging, I have found that if `resolvedExternals` remains as an empty set. The regex to be used will be `/\/@id\/()/g`. In this case it will match any line that contains `/@id/...`.
Example: `import _export_sfc from "/@id/__x00__plugin-vue:export-helper";`

I think we can fix this issue by simply verifying that the resolvedExternals is not empty before doing the replacement. I can push a PR to fix it.

**Comment by MilanKovacic** [comment]
Hi, PR would be appreciated.

**Comment by wassim-ben-amor** [comment]
PR created ✅
