### ISSUE TITLE
Plugin not rewriting references? Maybe user error

### ISSUE THREAD

**Issue by MaxWilson** [MilanKovacic/vite-plugin-externalize-dependencies#69]
Hi,

I'm trying to use this plugin for my FoundryVTT plugin. Before adding the plugin my .mjs had

```
import { createRoot } **from "react-dom/client"**;
import { printf, toConsole } from "./fable_modules/fable-library.4.4.1/String.js";
import { createElement } **from "react"**;
```

which cannot load in the browser because the browser doesn't know about my node_modules directory. After adding

```
**import externalize from "vite-plugin-externalize-dependencies";**
const config: UserConfig = ({
  **plugins: [react(),externalize({ externals: ["react", "react-dom"] })],**
```

I was hoping my imports would be different, e.g. "from ./react", so that I could gradually tweak it into finding the actual module path somehow. But my Program.js is unchanged.

Am I expecting too much from the vite plugin?

**Comment by MilanKovacic** [comment]
Hi, this plugin does quite the opposite of you are trying to achieve. Plugin actually blocks the rewriting of imports by Vite (esbuild) during development, so modules can be provided through externally, for example, through import maps.
